const { parsed: env } = require("dotenv").config();

module.exports = {
    DATABASE_URL: env.DATABASE_URL,
    JWT_SECRET_ACCESS: env.JWT_SECRET_ACCESS,
    JWT_SECRET_REFRESH: env.JWT_SECRET_REFRESH,
    JWT_SECRET_ACCESS_VERIFY: env.JWT_SECRET_ACCESS_VERIFY,
    EMAIL_USER: env.EMAIL_USER,
    EMAIL_PASS: env.EMAIL_PASS,
    CLIENT_URL: env.CLIENT_URL,
    API_URL: env.API_URL,
    PORT: env.PORT,
    CLOUDINARY_CLOUD_NAME: env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: env.CLOUDINARY_API_SECRET,
    POSTGRES_URL: env.POSTGRES_URL,
    POSTGRES_PRISMA_URL: env.POSTGRES_PRISMA_URL,
    POSTGRES_URL_NO_SSL: env.POSTGRES_URL_NO_SSL,
    POSTGRES_URL_NON_POOLING: env.POSTGRES_URL_NON_POOLING,
    POSTGRES_USER: env.POSTGRES_USER,
    POSTGRES_HOST: env.POSTGRES_HOST,
    POSTGRES_PASSWORD: env.POSTGRES_PASSWORD,
    POSTGRES_DATABASE: env.POSTGRES_DATABASE
};